version: 0.2
os: linux
files:
  - source: /
    destination: /home/ubuntu/CMUSICAL

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
